### ISSUE TITLE
只做了fcos的实验？

### ISSUE THREAD

**Issue by henbucuoshanghai** [Jia-Research-Lab/MSAD#4]
为什么选择fcos呢？

**Comment by qqlu** [comment]
Paper当中我们做了FCOS,retinaNet的detection实验，以及Mask-RCNN的instance segmentation和keypoint detection的实验

**Comment by henbucuoshanghai** [comment]
fcos很出名吗？

**Comment by qqlu** [comment]
是近几年很出色的一种one-stage detector

**Comment by henbucuoshanghai** [comment]
热心的回复，最后一个 &nbsp; &nbsp; 但是free一堆 centernet cornetnet extreent之类的不好吗？不出名？

**Comment by qqlu** [comment]
这些方法同样优秀出名。因时间和机器的问题，我们无法将所有的方法都尝试一遍，只能选择三四个方法。
